baseurl: /games
permalink: none
introduction: This is the home of YggiGames. Here you will find the results of tinkering with, hacking and creating various games. Some of what you find here may even be tested. Enjoy!
footer: Made with â˜• in Minneapolis. &copy;2018  Sam Kelley
description: The newest creations from YggiGames
short_name: YggiGames
name: YggiGames Blog
theme_color: "#DB3B1E"
analytics: false
sass:
  sass_dir: _sass
  style: compressed
